import { drizzle } from "drizzle-orm/mysql2";
import { crmClients, clientTasks, billingCharges } from "./drizzle/schema";

const db = drizzle(process.env.DATABASE_URL!);

async function seed() {
  console.log("🌱 Starting seed...");

  // CRM Clients
  const clients = await db.insert(crmClients).values([
    {
      clientName: "טכנולוגיות אלפא בע\"מ",
      contactPerson: "דני כהן",
      email: "danny@alpha-tech.co.il",
      phone: "050-1234567",
      businessType: "retainer",
      status: "active",
      monthlyRetainer: 15000,
      hourlyRate: null,
      bankHours: null,
      usedHours: 0,
      notes: "לקוח ריטיינר חודשי, תחזוקה שוטפת של אתר WordPress",
    },
    {
      clientName: "חנות הספרים המקוונת",
      contactPerson: "שרה לוי",
      email: "sarah@bookstore.co.il",
      phone: "052-9876543",
      businessType: "bank",
      status: "active",
      monthlyRetainer: null,
      hourlyRate: 350,
      bankHours: 50,
      usedHours: 12,
      notes: "בנק שעות של 50 שעות, נותרו 38 שעות",
    },
    {
      clientName: "סטודיו עיצוב קריאייטיב",
      contactPerson: "מיכאל אברהם",
      email: "michael@creative-studio.com",
      phone: "054-5551234",
      businessType: "hourly",
      status: "active",
      monthlyRetainer: null,
      hourlyRate: 400,
      bankHours: null,
      usedHours: 0,
      notes: "עבודה שעתית, פיתוח אתר תדמית חדש",
    },
    {
      clientName: "מסעדת הבשרים הטובה",
      contactPerson: "יוסי רוזנברג",
      email: "yossi@best-meat.co.il",
      phone: "03-6667788",
      businessType: "project",
      status: "active",
      monthlyRetainer: null,
      hourlyRate: null,
      bankHours: null,
      usedHours: 0,
      notes: "פרויקט בניית אתר חנות מקוונת - 45,000 ₪",
    },
    {
      clientName: "חברת ייעוץ עסקי פרימיום",
      contactPerson: "רונית שפירא",
      email: "ronit@premium-consulting.co.il",
      phone: "050-9998877",
      businessType: "retainer",
      status: "active",
      monthlyRetainer: 8000,
      hourlyRate: null,
      bankHours: null,
      usedHours: 0,
      notes: "ריטיינר חודשי לתחזוקה ועדכונים",
    },
    {
      clientName: "אפליקציית הבריאות החדשה",
      contactPerson: "ד\"ר אבי גולדשטיין",
      email: "avi@health-app.co.il",
      phone: "052-1112233",
      businessType: "project",
      status: "potential",
      monthlyRetainer: null,
      hourlyRate: null,
      bankHours: null,
      usedHours: 0,
      notes: "פוטנציאלי - פגישת היכרות בשבוע הבא",
    },
    {
      clientName: "חברת נדל\"ן יוקרתית",
      contactPerson: "גיא מזרחי",
      email: "guy@luxury-realestate.co.il",
      phone: "054-7778899",
      businessType: "bank",
      status: "active",
      monthlyRetainer: null,
      hourlyRate: 380,
      bankHours: 30,
      usedHours: 5,
      notes: "בנק שעות של 30 שעות, נותרו 25 שעות",
    },
    {
      clientName: "סטארטאפ פינטק חדש",
      contactPerson: "תומר ברק",
      email: "tomer@fintech-startup.com",
      phone: "050-4445566",
      businessType: "hourly",
      status: "inactive",
      monthlyRetainer: null,
      hourlyRate: 450,
      bankHours: null,
      usedHours: 0,
      notes: "לקוח לא פעיל - הפרויקט הוקפא",
    },
  ]);

  console.log("✅ Added 8 CRM clients");

  // Client Tasks
  await db.insert(clientTasks).values([
    {
      clientId: 1,
      taskName: "תיקון באג בטופס יצירת קשר",
      taskType: "development",
      status: "done",
      priority: "high",
      estimatedHours: 2,
      actualHours: 3,
      assignedTo: "עמית",
      dueDate: new Date("2024-10-20"),
      completedDate: new Date("2024-10-21"),
      billable: "included",
      notes: "תוקן - הבעיה הייתה בולידציה של שדה האימייל",
    },
    {
      clientId: 1,
      taskName: "עדכון תוכן בעמוד הבית",
      taskType: "support",
      status: "done",
      priority: "medium",
      estimatedHours: 1,
      actualHours: 1,
      assignedTo: "נירי",
      dueDate: new Date("2024-10-22"),
      completedDate: new Date("2024-10-22"),
      billable: "included",
      notes: "עודכן תוכן וגלריית תמונות",
    },
    {
      clientId: 2,
      taskName: "הוספת קטגוריה חדשה לחנות",
      taskType: "development",
      status: "in_progress",
      priority: "medium",
      estimatedHours: 4,
      actualHours: 2,
      assignedTo: "עמית",
      dueDate: new Date("2024-10-28"),
      completedDate: null,
      billable: "yes",
      notes: "בתהליך - נותרו עוד 2 שעות",
    },
    {
      clientId: 2,
      taskName: "אופטימיזציה של מהירות האתר",
      taskType: "development",
      status: "todo",
      priority: "high",
      estimatedHours: 6,
      actualHours: null,
      assignedTo: "עמית",
      dueDate: new Date("2024-11-05"),
      completedDate: null,
      billable: "yes",
      notes: "צריך לבדוק תמונות ולהוסיף caching",
    },
    {
      clientId: 3,
      taskName: "עיצוב דף About Us",
      taskType: "design",
      status: "review",
      priority: "medium",
      estimatedHours: 5,
      actualHours: 5,
      assignedTo: "אור",
      dueDate: new Date("2024-10-25"),
      completedDate: null,
      billable: "yes",
      notes: "ממתין לאישור לקוח",
    },
    {
      clientId: 3,
      taskName: "פיתוח דף יצירת קשר מותאם",
      taskType: "development",
      status: "todo",
      priority: "medium",
      estimatedHours: 8,
      actualHours: null,
      assignedTo: "עמית",
      dueDate: new Date("2024-11-10"),
      completedDate: null,
      billable: "yes",
      notes: "לאחר אישור העיצוב",
    },
    {
      clientId: 4,
      taskName: "בניית מערכת הזמנות מקוונת",
      taskType: "development",
      status: "in_progress",
      priority: "urgent",
      estimatedHours: 40,
      actualHours: 25,
      assignedTo: "עמית",
      dueDate: new Date("2024-11-15"),
      completedDate: null,
      billable: "included",
      notes: "פרויקט גדול - 60% הושלם",
    },
    {
      clientId: 4,
      taskName: "אינטגרציה עם מערכת משלוחים",
      taskType: "development",
      status: "todo",
      priority: "high",
      estimatedHours: 12,
      actualHours: null,
      assignedTo: null,
      dueDate: new Date("2024-11-20"),
      completedDate: null,
      billable: "included",
      notes: "תלוי בסיום מערכת ההזמנות",
    },
    {
      clientId: 5,
      taskName: "עדכון פלאגינים ו-WordPress",
      taskType: "support",
      status: "done",
      priority: "medium",
      estimatedHours: 1,
      actualHours: 1,
      assignedTo: "נירי",
      dueDate: new Date("2024-10-15"),
      completedDate: new Date("2024-10-15"),
      billable: "included",
      notes: "עודכן הכל לגרסה אחרונה",
    },
    {
      clientId: 5,
      taskName: "תיקון בעיית תצוגה במובייל",
      taskType: "development",
      status: "done",
      priority: "high",
      estimatedHours: 3,
      actualHours: 4,
      assignedTo: "עמית",
      dueDate: new Date("2024-10-18"),
      completedDate: new Date("2024-10-19"),
      billable: "included",
      notes: "תוקן - הבעיה הייתה ב-CSS",
    },
  ]);

  console.log("✅ Added 10 client tasks");

  // Billing Charges
  await db.insert(billingCharges).values([
    {
      clientId: 1,
      taskId: null,
      chargeType: "retainer",
      amount: 15000,
      hours: null,
      description: "ריטיינר חודשי - אוקטובר 2024",
      status: "paid",
      invoiceNumber: "INV-2024-10-001",
      invoiceDate: new Date("2024-10-01"),
      dueDate: new Date("2024-10-15"),
      paidDate: new Date("2024-10-12"),
      notes: "שולם במלואו",
    },
    {
      clientId: 2,
      taskId: 3,
      chargeType: "bank",
      amount: 700,
      hours: 2,
      description: "הוספת קטגוריה חדשה - 2 שעות",
      status: "pending",
      invoiceNumber: null,
      invoiceDate: null,
      dueDate: null,
      paidDate: null,
      notes: "ממתין לסיום המשימה",
    },
    {
      clientId: 3,
      taskId: 5,
      chargeType: "hourly",
      amount: 2000,
      hours: 5,
      description: "עיצוב דף About Us - 5 שעות",
      status: "invoiced",
      invoiceNumber: "INV-2024-10-015",
      invoiceDate: new Date("2024-10-25"),
      dueDate: new Date("2024-11-10"),
      paidDate: null,
      notes: "חשבונית נשלחה",
    },
    {
      clientId: 4,
      taskId: null,
      chargeType: "project",
      amount: 45000,
      hours: null,
      description: "פרויקט בניית אתר חנות מקוונת - תשלום ראשון (50%)",
      status: "paid",
      invoiceNumber: "INV-2024-09-025",
      invoiceDate: new Date("2024-09-15"),
      dueDate: new Date("2024-09-30"),
      paidDate: new Date("2024-09-28"),
      notes: "תשלום ראשון התקבל",
    },
    {
      clientId: 4,
      taskId: null,
      chargeType: "project",
      amount: 45000,
      hours: null,
      description: "פרויקט בניית אתר חנות מקוונת - תשלום שני (50%)",
      status: "pending",
      invoiceNumber: null,
      invoiceDate: null,
      dueDate: new Date("2024-11-30"),
      paidDate: null,
      notes: "ישולם בסיום הפרויקט",
    },
    {
      clientId: 5,
      taskId: null,
      chargeType: "retainer",
      amount: 8000,
      hours: null,
      description: "ריטיינר חודשי - אוקטובר 2024",
      status: "invoiced",
      invoiceNumber: "INV-2024-10-008",
      invoiceDate: new Date("2024-10-01"),
      dueDate: new Date("2024-10-15"),
      paidDate: null,
      notes: "חשבונית נשלחה, ממתין לתשלום",
    },
    {
      clientId: 7,
      taskId: null,
      chargeType: "bank",
      amount: 1900,
      hours: 5,
      description: "עבודות פיתוח שונות - 5 שעות",
      status: "paid",
      invoiceNumber: "INV-2024-10-012",
      invoiceDate: new Date("2024-10-20"),
      dueDate: new Date("2024-11-05"),
      paidDate: new Date("2024-10-22"),
      notes: "שולם במלואו",
    },
  ]);

  console.log("✅ Added 7 billing charges");
  console.log("🎉 Seed completed successfully!");
}

seed().catch(console.error);
