ALTER TABLE `client_tasks` ADD `subitem_support` text;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `owner` varchar(255);--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `group_name` varchar(255);--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `description` text;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `tech_notes` text;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `timeline_start` timestamp;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `timeline_end` timestamp;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `duration` int;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `files` text;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `dependency` text;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `automate` varchar(100);--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `files2` text;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `update_date` timestamp;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `updated_by` varchar(255);--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `change_log` text;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `previous_status` varchar(100);--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `previous_status_date` timestamp;--> statement-breakpoint
ALTER TABLE `client_tasks` ADD `crm_link` text;--> statement-breakpoint
ALTER TABLE `contacts` ADD `chat_link` varchar(500);--> statement-breakpoint
ALTER TABLE `contacts` ADD `whatsapp` varchar(50);--> statement-breakpoint
ALTER TABLE `contacts` ADD `whatsapp_web` varchar(500);--> statement-breakpoint
ALTER TABLE `contacts` ADD `flag` varchar(50);--> statement-breakpoint
ALTER TABLE `contacts` ADD `company_link` varchar(500);--> statement-breakpoint
ALTER TABLE `contacts` ADD `website_link` text;--> statement-breakpoint
ALTER TABLE `contacts` ADD `position2` varchar(255);--> statement-breakpoint
ALTER TABLE `contacts` ADD `mirror` text;--> statement-breakpoint
ALTER TABLE `contacts` ADD `project_link` text;--> statement-breakpoint
ALTER TABLE `contacts` ADD `project_link2` text;--> statement-breakpoint
ALTER TABLE `contacts` ADD `automate` varchar(100);--> statement-breakpoint
ALTER TABLE `contacts` ADD `accounts` text;--> statement-breakpoint
ALTER TABLE `contacts` ADD `list_dropdown` varchar(255);--> statement-breakpoint
ALTER TABLE `contacts` ADD `mirror2` text;--> statement-breakpoint
ALTER TABLE `contacts` ADD `crm_link` text;--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `priority` enum('low','medium','high','urgent') DEFAULT 'medium' NOT NULL;--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `description` text;--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `brief_description` varchar(500);--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `time_tracking` int;--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `asset_files` text;--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `brief_id` varchar(100);--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `creation_log` text;--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `work_figma` varchar(500);--> statement-breakpoint
ALTER TABLE `design_tasks` ADD `mirror` text;--> statement-breakpoint
ALTER TABLE `website_projects` ADD `login` varchar(500);--> statement-breakpoint
ALTER TABLE `website_projects` ADD `username` varchar(255);--> statement-breakpoint
ALTER TABLE `website_projects` ADD `password` varchar(255);--> statement-breakpoint
ALTER TABLE `website_projects` ADD `login_other` text;--> statement-breakpoint
ALTER TABLE `website_projects` ADD `copy_details` text;--> statement-breakpoint
ALTER TABLE `website_projects` ADD `contacts_link` text;--> statement-breakpoint
ALTER TABLE `website_projects` ADD `helper_http` varchar(500);--> statement-breakpoint
ALTER TABLE `website_projects` ADD `yat` varchar(255);--> statement-breakpoint
ALTER TABLE `website_projects` ADD `tasks_link` text;--> statement-breakpoint
ALTER TABLE `website_projects` ADD `creation_log` text;