CREATE TABLE `deals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deal_name` varchar(500) NOT NULL,
	`status` enum('active','won','lost','pending') NOT NULL DEFAULT 'active',
	`priority` enum('low','medium','high') NOT NULL DEFAULT 'medium',
	`value` decimal(12,2),
	`currency` varchar(10) DEFAULT 'ILS',
	`client` varchar(255),
	`contact_person` varchar(255),
	`phone` varchar(50),
	`email` varchar(320),
	`source` varchar(100),
	`stage` varchar(100),
	`probability` int,
	`expected_close_date` date,
	`actual_close_date` date,
	`assigned_to` varchar(255),
	`team` varchar(255),
	`notes` text,
	`tags` text,
	`files` text,
	`next_action` text,
	`last_contact` timestamp,
	`created_by` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deals_id` PRIMARY KEY(`id`)
);
