CREATE TABLE `payment_collection` (
	`id` int AUTO_INCREMENT NOT NULL,
	`item` varchar(500) NOT NULL,
	`subitem` varchar(500),
	`amount` decimal(12,2),
	`target_date` date,
	`payment_date` date,
	`date_diff` int,
	`collection_status` enum('pending','in_progress','collected','overdue') NOT NULL DEFAULT 'pending',
	`payment_status` enum('not_paid','partial','paid','cancelled') NOT NULL DEFAULT 'not_paid',
	`documents` text,
	`link` varchar(500),
	`notes` text,
	`tags` text,
	`account` varchar(255),
	`email` varchar(320),
	`phone` varchar(50),
	`contacts` text,
	`website` varchar(500),
	`currency` varchar(10) DEFAULT 'ILS',
	`amount_ils` decimal(12,2),
	`automation` text,
	`created_by` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payment_collection_id` PRIMARY KEY(`id`)
);
